[build]
  functions = "service"

[[redirects]]
  from = "/people*"
  to = "/"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  REACT_APP_POLICY_ROOT = "Policy root"
  POLICY_ID = "Policy ID"
  TENANT_ID = "Aserto tenant ID"
  AUTHORIZER_API_KEY = "Aserto authorizer API key"
  REACT_APP_NETLIFY = "Netlify flag must be set to NETLIFY"
  REACT_APP_DEX_DOMAIN="Aserto Demo Domain (acmecorp.demo.aserto.com)"
  REACT_APP_DEX_CLIENT_ID="Demo Client ID (acmecorp-app)"
  REACT_APP_DEX_AUDIENCE="Demo Audience (acmecorp-app)"

[context.production]
  publish = "build/"
  command = "yarn build"
